approve_by_comment: true
approve_regex: ^(Approved|LGTM)
reject_regex: ^Rejected
reset_on_push: true
author_approval: required
reset_on_reopened: true

reviewers:
  -
    name: "Master Merge Approvers"
    required: 1
    teams:
      - master-merge-approvers
