approve_by_comment: true
approve_regex: ^Approved
reject_regex: ^Rejected
reset_on_push: true
author_approval: required

reviewers:
  -
      name: admins
      required: 1
      members:
        - fred333
        - bradmiller
        - peterjohnson
        - jlleitscuh
  -
      name: core_devs
      required: 1
      members:
        - thadhouse
        - virtuald
        - patrickpenguinturtle
        - petermitrano
