sudo: required
dist: trusty
language: java

before_install:
  - sudo sh -c 'echo "deb http://packages.osrfoundation.org/gazebo/ubuntu-stable `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-stable.list'
  - wget http://packages.osrfoundation.org/gazebo.key -O - | sudo apt-key add -
  - sudo add-apt-repository ppa:wpilib/toolchain -y
  - sudo apt-get update -q || true
  - sudo apt-get install frc-toolchain libgazebo7-dev protobuf-compiler libprotobuf-dev -y


before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
 - ./gradlew build -PmakeSim
 
