# Job for building

parameters:
  jobName: ''
  pool:
    vmImage: 'Ubuntu 16.04'
  container: wpilib2020
  preBuild: []
  jdkVersionOption: ''
  buildOptions: ''
  artifactName: ''

jobs:
- job: ${{ parameters.jobName }}
  pool: ${{ parameters.pool }}

  ${{ if ne(parameters.container, '') }}:
    container: ${{ parameters.container }}

  workspace:
    clean: all

  timeoutInMinutes: 0

  steps:
    - ${{ parameters.preBuild }}

    - template: build-steps.yml
      parameters:
        jdkVersionOption: ${{ parameters.jdkVersionOption }}
        buildOptions: ${{ parameters.buildOptions }}
        artifactName: ${{ parameters.artifactName }}
