# Stage to combine artifacts into a single output

parameters:
  publish: False
  artifacts: []

stages:
- stage: Combine
  jobs:
  - job: CombineJob
    pool:
      vmImage: 'macOS-10.14'

    timeoutInMinutes: 0

    steps:
    - checkout: none

    - script: |
        git clone https://github.com/wpilibsuite/build-tools
      displayName: 'Clone Combiner'

    ${{ each artifact in parameters.artifacts }}:
      ${{ artifact }}:
        - task: DownloadPipelineArtifact@0
          inputs:
            artifactName: ${{ artifact }}
            targetPath: 'build-tools/combiner/products/build/allOutputs'

# PR Builds
    - task: Gradle@2
      inputs:
        workingDirectory: 'build-tools/combiner'
        gradleWrapperFile: 'build-tools/combiner/gradlew'
        gradleOptions: '-Xmx3072m'
        tasks: 'publish '
        options: '-Pallwpilib'
      condition: and(succeeded(), and(ne(variables['Build.SourceBranch'], 'refs/heads/master'), not(startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))))

    - ${{ if parameters.publish }}:
# Master Builds
      - task: Gradle@2
        inputs:
          workingDirectory: 'build-tools/combiner'
          gradleWrapperFile: 'build-tools/combiner/gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'publish '
          options: '-Pallwpilib'
        condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: $(PublishUserName)
          ARTIFACTORY_PUBLISH_PASSWORD: $(PublishPassword)

# Tagged Builds
      - task: Gradle@2
        inputs:
          workingDirectory: 'build-tools/combiner'
          gradleWrapperFile: 'build-tools/combiner/gradlew'
          gradleOptions: '-Xmx3072m'
          tasks: 'publish '
          options: '-Pallwpilib -PreleaseRepoPublish'
        condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags/v'))
        env:
          RUN_AZURE_ARTIFACTORY_RELEASE: 'TRUE'
          ARTIFACTORY_PUBLISH_USERNAME: $(PublishUserName)
          ARTIFACTORY_PUBLISH_PASSWORD: $(PublishPassword)

    - script: |
        echo "##vso[task.setvariable variable=UserHome]$HOME"
      displayName: 'Set Home Variable'
    - task: PublishPipelineArtifact@0
      inputs:
        artifactName: 'Maven'
        targetPath: $(UserHome)/releases
