name: Artifactory Nightly Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: '15 2 * * *'

jobs:
  wpilib-mvn-development_unused_cleanup:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wpilibsuite' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ENV_1: !! REPLACE ME !!
      - name: Cleanup
        run: jf rt del --spec=.github/workflows/aql/wpilib-mvn-development_unused.aql

  wpilib-generic-gradle-cache_unused_cleanup:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'wpilibsuite' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: jfrog/setup-jfrog-cli@v4
        env:
          JF_ENV_1:  !! REPLACE ME !!
      - name: Cleanup
        run: jf rt del --spec=.github/workflows/aql/wpilib-generic-gradle-cache_unused.aql
