name: "Validate Gradle Wrapper"
on: [pull_request, push]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: gradle/wrapper-validation-action@v1
